// @generated by Thrift for src/interface/common.thrift
// This file is probably not the place you want to edit!

#![recursion_limit = "100000000"]
#![allow(bare_trait_objects)]
#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals, unused_crate_dependencies, clippy::all)]

pub use self::consts::*;
pub use self::errors::*;
pub use self::types::*;

/// Constant definitions for `common`.
pub mod consts {
    // pub const version: ::std::vec::Vec<::std::primitive::u8> = "3.0.0".as_bytes().into();
}

pub mod types;

/// Error return types.
pub mod errors {
}
pub mod double;
