name: pull_request

on:
  pull_request:
    branches:
      - master
      - 'v[0-9]+.*'
  schedule:
    - cron:  '0 18 * * *'


defaults:
  run:
    shell: bash

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup tool chain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          rustup component add clippy
      - name: Lint
        run: |
          cargo clippy
      - name: Build
        run: |
          cargo build --release
      - name: Nebula Server
        run: |
          sudo curl -sSL https://get.docker.com/ | sh
          pip3 install --upgrade pip
          pip3 install setuptools
          pip3 install docker-compose
          mkdir tmp
          pushd tmp
          git clone --depth=1 https://github.com/vesoft-inc/nebula-docker-compose.git
          pushd nebula-docker-compose/
          docker-compose up -d
          sleep 3
          popd
          popd
      - name: test
        run: |
          cargo test
        timeout-minutes: 4
      - name: example
        run: |
          cargo run --example basic_op
        timeout-minutes: 4
